### ISSUE TITLE
Switch to manylinux2010-compatible wheels

### ISSUE THREAD

**Issue by lonvia** [osmcode/pyosmium-wheel-build#4]
[PEP571](https://www.python.org/dev/peps/pep-0571/) has been out for a while and we should switch to providing manylinux2010-compatible wheels. @wiktorn would you have time to look into this?

**Comment by wiktorn** [comment]
Sure, I'll take this one. Also will take into consideration osmcode/pyosmium#123

**Comment by lonvia** [comment]
Great, thanks. I tried to update pybind11 as this was suggested as a possible solution to https://github.com/osmcode/pyosmium/issues/123 but the last build [failed completely](https://travis-ci.org/osmcode/pyosmium-wheel-build/builds/646170665) on something that looks completely unrelated. Hopefully that gets fixed with an updated manylinux as well..

**Comment by wiktorn** [comment]
The build failed because of API change in pip, see: matthew-brett/multibuild#298, this is fixed in devel branch of multibuild.

For now, the builds fail on the other issue (on macOS, only python2.7): matthew-brett/multibuild#305 for which I hope there is simple workaround.

Python3.4 is no longer supported on macOS so I dropped it in `.travis.yml`

Waiting for [build](https://travis-ci.org/wiktorn/pyosmium-wheel-build/builds/649537691) results.

As far as I tested (python3.6) this fixes osmcode/pyosmium#123.
